language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.1

services:
  - redis-server

env:
  - NETTE=nette-2.3

before_install:
  - travis_retry composer self-update
  - wget -O /tmp/composer-nette https://raw.githubusercontent.com/Kdyby/TesterExtras/master/bin/composer-nette.php
  - php /tmp/composer-nette

addons:
  apt:
    packages:
      - redis-server

install:
  - travis_retry composer update --no-interaction --prefer-dist
  - travis_retry composer create-project --no-interaction jakub-onderka/php-parallel-lint /tmp/php-parallel-lint
  - tests/travis.phpredis.sh
  - redis-cli info |grep version

script:
  - vendor/bin/tester -s -c ./tests/php.ini-unix ./tests/KdybyTests/
  - php /tmp/php-parallel-lint/parallel-lint.php -e php,phpt --exclude vendor .

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
